---
title: "Client Report - [Insert Project Title]"
subtitle: "Course DS 250"
author: "[STUDENT NAME]"
format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: See code
execute: 
  warning: false
    
---


```{python}
import pandas as pd
import numpy as np
from lets_plot import *

LetsPlot.setup_html(isolated_frame=True)
```


## Project Notes

__For Project 1 the answer to each question should include a chart **and** a written response. The years labels on your charts should not include a comma. At least **two** of your charts must include reference marks.__  

```{python}
# Learn morea about Code Cells: https://quarto.org/docs/reference/cells/cells-jupyter.html

# Include and execute your code here
df = pd.read_csv("https://raw.githubusercontent.com/byuidatascience/data4names/master/data-raw/names_year/names_year.csv")
```

## QUESTION|TASK 1

__How does your name at your birth year compare to its use historically?__

_type your results and analysis here_

```{python}
df.head()
df_Tanner = df.query("name == 'Tanner'")
df_Tanner.head()
print(df_Tanner.dtypes)
```



```{python}


(
  ggplot(df_Tanner, aes(x = 'year', y = 'Total')) + 
geom_line() +
labs(
  x = "Year",
  title = "Tanner is becoming less popular"
) +
geom_vline(xintercept = "2002", color = "red") +
  theme_bw() +
  geom_text(aes(x=[2001], y=[15], label=["Year I was born"]), size=8, color='red',hjust = 1)


)



# print("Hello")


```



## QUESTION|TASK 2

__If you talked to someone named Brittany on the phone, what is your guess of his or her age? What ages would you not guess?__

_type your results and analysis here_

```{python}
df_Brittany = df.query("name == 'Brittany'") 
df_Brittany.head()




```

```{python}
(ggplot(df_Brittany, aes(x = "year", y = "Total")) +
  geom_line() +
  geom_vline(xintercept=1990, linetype=2, color='red', alpha=0.5) +
  labs(title = "Most Brittanys born in 1990" , x = "Year"
  
  )
  
  
  )




```
## QUESTION|TASK 3

__Mary, Martha, Peter, and Paul are all Christian names. From 1920 - 2000, compare the name usage of each of the four names in a single chart. What trends do you notice?__

_type your results and analysis here_

```{python}
# names =
df_bible = df.query("name in ['Mary', 'Martha', 'Peter', 'Paul']")

```

```{python}
(ggplot(df_bible, aes( x = "year", y = "Total", color = "name")) +
  # geom_jitter() +
  geom_line() +
  scale_color_manual(values=["red","blue","green","yellow"]) +
  labs(title = "Biblical names are becoming less popular") +
  theme_bw()

)
```

## QUESTION|TASK 4

__Think of a unique name from a famous movie. Plot the usage of that name and see how changes line up with the movie release. Does it look like the movie had an effect on usage?__  

_type your results and analysis here_

```{python}
df_Anakin = df.query("name == 'Anakin'")
df_Anakin.head()

```

```{python}
(ggplot(df_Anakin, aes(x = "year", y = "Total")) +
geom_line() +
labs(title = "Anakin is getting more popular", x = "Years") +
geom_vline(xintercept = "1999", color = "darkgreen") +
geom_vline(xintercept = "2002", color = "blue") +
geom_vline(xintercept = "2005", color = "red") +
geom_text(aes(x=[1999], y=[65], label=["Episode I"]), size=8, color='darkgreen',hjust = 0) +
geom_text(aes(x=[2002], y=[25], label=["Episode II"]), size=8, color='blue',hjust = 0) +
geom_text(aes(x=[2005], y=[100], label=["Episode III"]), size=8, color='red',hjust = 0)

)
```
---

## STRETCH QUESTION|TASK 1
<!-- 
__Reproduce the chart Elliot using the data from the `names_year.csv` file.__ 

_type your results and analysis here_

```{python}
# Include and execute your code here


```


--- -->
